### ISSUE TITLE
How to install tectosaur?

### ISSUE THREAD

**Issue by tututingting** [tbenthompson/tectosaur#1]
I want to install tectosaur, and run the examples. But there are no instructions.

**Comment by tbenthompson** [comment]
Hey, I'm not planning to support usage for a little while longer. To quote the readme: "Further documentation and examples will absolutely be available in the future! Until then, however, tectosaur will be rapidly changing and developing and any users should expect little to no support and frequent API breaking changes." 

I'll let you know when I get some instructions up and am ready to support this. I just don't have time right now.
