### ISSUE TITLE
"RuntimeError: Cannot run the event loop while another loop is running" when running examples

### ISSUE THREAD

**Issue by sebarra1477** [tbenthompson/tectosaur#3]
Hi Ben, 
I installed the tectosaur, on python 3.8 and i installed pyopencl (i don't have an Nvidia).
 The installation seems successful, until i run the example "okada.ipynb" (on jupyter notebook),  in the construction of the C^{t} Ar:
rhs_constrained = cm.T.dot(-lhs.dot(c_rhs))
 i had
> "RuntimeError: Cannot run the event loop while another loop is running".

 I had the same error in the fault_traction notebook. In the line:
rhs = -cm.T.dot(H.dot(slip.flatten())) - cm.T.dot(traction_mass_op.mat.dot(c_rhs))
My operating system is ubuntu 18.04. Would you give me some suggestions?

**Comment by tbenthompson** [comment]
Unfortunately, I'm not maintaining this package anymore.

That said, I believe the issue you're running into has to do with an incompatibility between `asyncio` and Jupyter. If you run from a python prompt or a subprocess, it should work fine.
