### ISSUE TITLE
Request for the 'edge_adj_setup.py' file which was used in tectosaur

### ISSUE THREAD

**Issue by vic-chou** [tbenthompson/tectosaur#4]
Hi Ben,

When I use the tectosaur, I meet a problem. When I tried to run 'import inverse_tools', the screen prompted that 'ModuleNotFoundError: No modul named 'tectosaur.nearfield.edge_adj_setup''. I also can not find 'edge_adj_setup.py' file in the fold '/tedtosaur/nearfield'. Can you provide me this file?

Best regards,
Guangyu

**Comment by tbenthompson** [comment]
Unfortunately, I'm not maintaining this package anymore.
